spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./test.db
    hikari:
      maximum-pool-size: 1

  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
